// ============================================
// SciENcv Biosketch - Create New Document
// Generated by Claude in Chrome browser extension
// ============================================

// SELECTORS
const CREATE_DOCUMENT_SELECTORS = {
  newDocumentButton: 'button "NEW DOCUMENT"',
  documentNameField: 'textbox "Document Name *"',
  documentTypeButton: 'button "Document type"',
  externalSourceRadio: 'radio "Use an external source"',
  existingDocumentRadio: 'radio "Use an existing document in SciENcv"',
  blankDocumentRadio: 'radio "Start with a blank document"',
  sourceDropdown: 'combobox "Source *"',
  documentDropdown: 'combobox "Document *"',
  createButton: 'button "CREATE"'
};

// Document Type Options:
// - "NIH Biographical Sketch Common Form"
// - "NSF Biographical Sketch"
// - "IES Biographical Sketch"
// - etc.

// External Source Options:
// - "eRA Commons"
// - "ORCiD"

// CONFIGURATION EXAMPLE
const newDocumentConfig = {
  documentName: "My New R01 Biosketch",
  documentType: "NIH Biographical Sketch Common Form",
  dataSource: "blank", // Options: "external", "existing", "blank"
  // Only if dataSource is "external":
  externalSource: "eRA Commons", // or "ORCiD"
  // Only if dataSource is "existing":
  existingDocument: "Parker Master biosketc"
};

// AUTOMATION FUNCTION
async function createNewDocument(config) {
  // 1. Navigate to SciENcv home page
  await navigate('https://www.ncbi.nlm.nih.gov/labs/sciencv/');

  // 2. Click NEW DOCUMENT button
  await click('button "NEW DOCUMENT"');

  // 3. Wait for dialog to open
  await waitForElement('textbox "Document Name *"');

  // 4. Enter Document Name
  await formInput('textbox "Document Name *"', config.documentName);

  // 5. Select Document Type
  await click('button "Document type"');
  await waitForElement(`option "${config.documentType}"`);
  await click(`option "${config.documentType}"`);

  // 6. Select Data Source
  switch (config.dataSource) {
    case "external":
      await click('radio "Use an external source"');
      // Wait for Source dropdown to appear
      await waitForElement('combobox "Source *"');
      await click('combobox "Source *"');
      await click(`option "${config.externalSource}"`);
      break;

    case "existing":
      await click('radio "Use an existing document in SciENcv"');
      // Wait for Document dropdown to appear
      await waitForElement('combobox "Document *"');
      await click('combobox "Document *"');
      await click(`option "${config.existingDocument}"`);
      break;

    case "blank":
    default:
      await click('radio "Start with a blank document"');
      break;
  }

  // 7. Click CREATE button
  await click('button "CREATE"');

  // 8. Wait for navigation to new document
  await waitForNavigation();

  // Returns the new document URL
  return getCurrentUrl();
}

// EXAMPLE USAGE

// Create blank NIH biosketch
// const docUrl = await createNewDocument({
//   documentName: "Parker K99 Application",
//   documentType: "NIH Biographical Sketch Common Form",
//   dataSource: "blank"
// });

// Copy from existing document
// const copiedDocUrl = await createNewDocument({
//   documentName: "Parker R21 Application",
//   documentType: "NIH Biographical Sketch Common Form",
//   dataSource: "existing",
//   existingDocument: "Parker Master biosketc"
// });

// Import from eRA Commons
// const importedDocUrl = await createNewDocument({
//   documentName: "Parker New Grant",
//   documentType: "NIH Biographical Sketch Common Form",
//   dataSource: "external",
//   externalSource: "eRA Commons"
// });
