// ============================================
// SciENcv Biosketch - NIH Biographical Sketch
// Section C: Products
// Generated by Claude in Chrome browser extension
// ============================================

// SELECTORS
const PRODUCTS_SELECTORS = {
  selectRelatedButton: 'button "SELECT RELATED PRODUCTS"',
  selectOtherButton: 'button "SELECT OTHER PRODUCTS"',
  searchInput: 'textbox "Search citations"',
  citationCheckbox: 'checkbox "Citation for:"',
  continueButton: 'button "CONTINUE"'
};

// Note: Each section allows up to 5 products
// Products are selected by searching for PMID

// PRODUCTS DATA EXAMPLE
const relatedProducts = [
  { pmid: "29666020", title: "Geographic Variation" },
  { pmid: "31714985", title: "Association of Transplant Center" },
  { pmid: "32527399", title: "Practice Changes" },
  { pmid: "38349372", title: "US-CRS Development" },
  { pmid: "40080116", title: "CLIF consortium" }
];

const otherProducts = [
  { pmid: "29246896", title: "Inotropes" },
  { pmid: "33864733", title: "Between-Center Variation" },
  { pmid: "34951528", title: "Post-transplant Survival" },
  { pmid: "26760565", title: "Kidney Donor Profile Index" },
  { pmid: "39804637", title: "UDNR Orders" }
];

// AUTOMATION FUNCTION
async function addProducts(productList, buttonSelector) {
  // 1. Click SELECT button to open selection panel
  await click(buttonSelector);

  for (const product of productList) {
    // 2. Find and clear search input
    const searchInput = await find('textbox "Search citations"');
    await tripleClick(searchInput);

    // 3. Type PMID
    await type(product.pmid);

    // 4. Press Enter to search
    await pressKey('Return');

    // 5. Wait for results
    await waitForElement(`checkbox "Citation for:"`);

    // 6. Click checkbox to select citation
    const checkbox = await find(`checkbox "Citation for:"`);
    await click(checkbox);
  }

  // 7. Click CONTINUE to save selections
  await click('button "CONTINUE"');
}

// Execute for both sections
// await addProducts(relatedProducts, 'button "SELECT RELATED PRODUCTS"');
// await addProducts(otherProducts, 'button "SELECT OTHER PRODUCTS"');
