// ============================================
// SciENcv Biosketch - Section B: Appointments and Positions
// Target: https://www.ncbi.nlm.nih.gov/labs/sciencv/[document_id]
// Generated by Claude in Chrome browser extension
// ============================================

// SELECTORS (CSS)
const SELECTORS = {
  addButton: 'button:contains("ADD APPOINTMENT/POSITION")', // or find by text
  positionTitle: 'input[type="text"]', // First text input in dialog - label "Appointment or Position Title *"
  organization: 'input[type="text"]',  // Second text input - label "Name of Organization/Department"
  city: 'input[type="text"]',          // Third text input - label "City *"
  stateDropdown: '[aria-haspopup="listbox"]', // or combobox with label "State/Province *"
  startYear: 'input[type="tel"][placeholder="yyyy"]', // First year input
  endYear: 'input[type="tel"][placeholder="yyyy"]',   // Second year input
  saveAndAdd: 'button:contains("SAVE & ADD ANOTHER ENTRY")',
  save: 'button:contains("SAVE")',
  cancel: 'button:contains("CANCEL")'
};

// POSITION DATA EXAMPLE
const positions = [
  {
    title: "Co-Chair",
    organization: "Scientific Registry of Transplant Recipients Analytic Methods Subcommittee",
    city: "Minneapolis",
    state: "Minnesota",
    startYear: "2025",
    endYear: null  // null = Present
  },
  {
    title: "Member",
    organization: "Scientific Registry of Transplant Recipients Analytic Methods Subcommittee",
    city: "Minneapolis",
    state: "Minnesota",
    startYear: "2023",
    endYear: "2024"
  },
  {
    title: "Section Editor",
    organization: "The Journal of Heart and Lung Transplantation",
    city: "New York",
    state: "New York",
    startYear: "2023",
    endYear: null
  },
  {
    title: "Assistant Director",
    organization: "MacLean Center for Clinical Medical Ethics",
    city: "Chicago",
    state: "Illinois",
    startYear: "2021",
    endYear: null
  },
  {
    title: "Assistant Professor of Medicine and Public Health Sciences",
    organization: "University of Chicago",
    city: "Chicago",
    state: "Illinois",
    startYear: "2021",
    endYear: "2024"
  },
  {
    title: "Instructor, Pulmonary and Critical Care Medicine",
    organization: "University of Chicago",
    city: "Chicago",
    state: "Illinois",
    startYear: "2019",
    endYear: "2021"
  },
  {
    title: "Fellow, Pulmonary and Critical Care Medicine",
    organization: "University of Chicago",
    city: "Chicago",
    state: "Illinois",
    startYear: "2015",
    endYear: "2019"
  },
  {
    title: "Resident, Internal Medicine",
    organization: "University of Chicago",
    city: "Chicago",
    state: "Illinois",
    startYear: "2012",
    endYear: "2015"
  }
];

// AUTOMATION STEPS FOR EACH POSITION
function addPosition(position, isLast) {
  // Step 1: Click "ADD APPOINTMENT/POSITION" button
  // await page.click('button:has-text("ADD APPOINTMENT/POSITION")');

  // Step 2: Fill Position Title
  // await page.fill('input[aria-label*="Position Title"]', position.title);

  // Step 3: Fill Organization
  // await page.fill('input[aria-label*="Organization"]', position.organization);

  // Step 4: Fill City
  // await page.fill('input[aria-label*="City"]', position.city);

  // Step 5: Select State (dropdown)
  // await page.click('[aria-label*="State/Province"]');
  // await page.type(position.state);
  // await page.keyboard.press('Enter');

  // Step 6: Fill Start Year
  // await page.fill('input[placeholder="yyyy"]:first', position.startYear);

  // Step 7: Fill End Year (if not present)
  // if (position.endYear) {
  //   await page.fill('input[placeholder="yyyy"]:last', position.endYear);
  // }

  // Step 8: Save
  // if (isLast) {
  //   await page.click('button:has-text("SAVE")');
  // } else {
  //   await page.click('button:has-text("SAVE & ADD ANOTHER ENTRY")');
  // }
}
