// ============================================
// SciENcv Biosketch - NIH Biographical Sketch
// Section A: Professional Preparation (Education)
// Generated by Claude in Chrome browser extension
// ============================================

// SELECTORS
const EDUCATION_SELECTORS = {
  addButton: 'button "ADD PROFESSIONAL PREPARATION"',
  organizationField: 'textbox "Organization *"',
  cityField: 'textbox "City *"',
  countryDropdown: 'combobox "Country *"',
  stateDropdown: 'combobox "State/Province *"',
  degreeDropdown: 'combobox "Degree *"',
  fieldOfStudyField: 'textbox "Field of Study *"',
  startDateField: 'textbox "Start Date"',
  endDateField: 'textbox "End Date"',
  trainingRadio: 'radio "Training"',
  degreeRadio: 'radio "Degree"', // default
  saveButton: 'button "SAVE"',
  saveAndAddButton: 'button "SAVE & ADD ANOTHER ENTRY"'
};

// Note: Type can be "Degree" (default) or "Training"
// Training includes: Postdoctoral, Fellowship, Residency, etc.

// EDUCATION DATA EXAMPLE
const educationEntries = [
  {
    type: "Degree",
    organization: "Williams College",
    city: "Williamstown",
    country: "United States",
    state: "Massachusetts",
    degree: "Bachelor of Arts (BA)",
    field: "Physics",
    startDate: "09/2004",
    endDate: "06/2008"
  },
  {
    type: "Degree",
    organization: "University of Chicago",
    city: "Chicago",
    country: "United States",
    state: "Illinois",
    degree: "Doctor of Medicine (MD)",
    field: "Medicine",
    startDate: "09/2008",
    endDate: "06/2012"
  },
  {
    type: "Training",
    organization: "University of Chicago",
    city: "Chicago",
    country: "United States",
    state: "Illinois",
    degree: "Resident",
    field: "Internal Medicine",
    startDate: "07/2012",
    endDate: "06/2015"
  }
  // ... additional entries
];

// AUTOMATION FUNCTION
async function addProfessionalPreparation(entry, isLast = false) {
  // 1. Click ADD PROFESSIONAL PREPARATION button
  await click('button "ADD PROFESSIONAL PREPARATION"');

  // 2. Wait for dialog to open
  await waitForElement('textbox "Organization *"');

  // 3. Select Type (Degree or Training)
  if (entry.type === "Training") {
    await click('radio "Training"');
  }
  // Degree is default, no click needed

  // 4. Fill Organization
  await formInput('textbox "Organization *"', entry.organization);

  // 5. Fill City
  await formInput('textbox "City *"', entry.city);

  // 6. Select Country (if not United States)
  if (entry.country !== "United States") {
    await click('combobox "Country *"');
    await type(entry.country);
    await pressKey('Return');
  }

  // 7. Select State/Province
  await click('combobox "State/Province *"');
  await type(entry.state.substring(0, 4)); // Type first few chars to filter
  await pressKey('Return');

  // 8. Select Degree
  await click('combobox "Degree *"');
  await type(entry.degree.split(' ')[0]); // Type first word to filter
  // Find and click the matching option
  await click(`option "${entry.degree}"`);

  // 9. Fill Field of Study
  await formInput('textbox "Field of Study *"', entry.field);

  // 10. Fill Start Date
  await formInput('textbox "Start Date"', entry.startDate);

  // 11. Fill End Date
  await formInput('textbox "End Date"', entry.endDate);

  // 12. Save
  if (isLast) {
    await click('button "SAVE"');
  } else {
    await click('button "SAVE & ADD ANOTHER ENTRY"');
  }
}

// Execute for all entries
// for (let i = 0; i < educationEntries.length; i++) {
//   const isLast = (i === educationEntries.length - 1);
//   await addProfessionalPreparation(educationEntries[i], isLast);
// }
