// ============================================
// SciENcv Biosketch - NIH Biographical Sketch Supplement
// Section C: Contributions to Science
// Generated by Claude in Chrome browser extension
// ============================================

// SELECTORS
const CONTRIBUTIONS_SELECTORS = {
  addButton: 'button:contains("ADD CONTRIBUTION TO SCIENCE")',
  addAnotherButton: 'button:contains("ADD ANOTHER CONTRIBUTION TO SCIENCE")',
  descriptionField: 'textarea', // or textbox with label "Description"
  saveButton: 'button:contains("SAVE")',
  cancelButton: 'button:contains("CANCEL")',
  editButton: 'button:contains("EDIT")',
  deleteButton: 'button:contains("DELETE")',
  upButton: 'button:contains("UP")',
  downButton: 'button:contains("DOWN")'
};

// Note: Character limit is 2,000 per contribution
// Note: Maximum 5 contributions allowed

// CONTRIBUTIONS DATA EXAMPLE
const contributions = [
  {
    title: "Contribution 1",
    description: `Description text here (up to 2,000 characters)...`,
    // Citations are added separately after the contribution is saved
    citations: []
  }
  // ... up to 5 contributions
];

// AUTOMATION FUNCTION
async function addContributions(page, contributions) {
  for (let i = 0; i < contributions.length; i++) {
    const contrib = contributions[i];
    const isFirst = i === 0;

    // Step 1: Click add button
    // if (isFirst) {
    //   await page.click('button:has-text("ADD CONTRIBUTION TO SCIENCE")');
    // } else {
    //   await page.click('button:has-text("ADD ANOTHER CONTRIBUTION TO SCIENCE")');
    // }

    // Step 2: Fill description (2,000 char limit)
    // await page.fill('textarea', contrib.description);

    // Step 3: Save
    // await page.click('button:has-text("SAVE")');

    // Step 4: Add citations (if any) - this may require additional steps
    // Citations are typically added via a separate dialog after saving the contribution
  }
}

// CITATION ADDING (separate workflow after contribution is saved)
// The citation workflow typically involves:
// 1. Click "ADD CITATION" or similar button on the saved contribution
// 2. Search by PMID, DOI, or title
// 3. Select the citation from search results
// 4. Save
