// ============================================
// SciENcv Biosketch - NIH Biographical Sketch Supplement
// Section B: Honors
// Generated by Claude in Chrome browser extension
// ============================================

// SELECTORS
const HONORS_SELECTORS = {
  addButton: 'button:contains("ADD HONOR")',
  honorField: 'input[type="text"]',  // First text input - label "Honor *"
  organizationField: 'input[type="text"]', // Second text input - label "Name of Organization *"
  yearField: 'input[type="tel"][placeholder="yyyy"]', // Year field
  endYearField: 'input[type="tel"][placeholder="yyyy"]', // End Year (optional, for date ranges)
  saveAndAddButton: 'button:contains("SAVE & ADD ANOTHER")',
  saveButton: 'button:contains("SAVE")',
  cancelButton: 'button:contains("CANCEL")'
};

// HONORS DATA EXAMPLE (reverse chronological order)
const honors = [
  {
    honor: "John D. Arnold, MD Scientific Research Prize for outstanding medical student mentorship (student mentee Lazenby)",
    organization: "Pritzker School of Medicine, University of Chicago",
    year: "2024"
  },
  {
    honor: "John D. Arnold, MD Scientific Research Prize for outstanding medical student mentorship (student mentee Chung)",
    organization: "Pritzker School of Medicine, University of Chicago",
    year: "2023"
  },
  {
    honor: "Best Dissertation, Department of Public Health Sciences",
    organization: "University of Chicago",
    year: "2021"
  },
  {
    honor: "Young Physician-Scientist Award",
    organization: "American Society for Clinical Investigation",
    year: "2020"
  },
  {
    honor: "Ziskind Clinical Research Scholar Award",
    organization: "American Thoracic Society",
    year: "2018"
  },
  {
    honor: "Outstanding Clinical Service Award",
    organization: "University of Chicago Medicine",
    year: "2016"
  },
  {
    honor: "Franklin McLean Medical Student Research Award for a fourth-year student who has performed the most meritorious research",
    organization: "Pritzker School of Medicine, University of Chicago",
    year: "2012"
  },
  {
    honor: "Calvin Fentress Research Fellowship",
    organization: "University of Chicago",
    year: "2011"
  },
  {
    honor: "Alpha Omega Alpha Honor Society",
    organization: "Alpha Omega Alpha",
    year: "2011"
  },
  {
    honor: "Fellowships at Auschwitz for the Study of Professional Ethics (FASPE). Highly selective international summer program investigating the role of medical professionals in the Holocaust.",
    organization: "FASPE",
    year: "2010"
  }
];

// AUTOMATION FUNCTION
async function addHonors(page, honors) {
  for (let i = 0; i < honors.length; i++) {
    const honor = honors[i];
    const isLast = i === honors.length - 1;

    // Step 1: Click "ADD HONOR" (only needed for first entry if dialog not already open)
    // if (i === 0) await page.click('button:has-text("ADD HONOR")');

    // Step 2: Fill Honor field
    // await page.fill('input:near(:text("Honor *"))', honor.honor);

    // Step 3: Fill Organization field
    // await page.fill('input:near(:text("Name of Organization *"))', honor.organization);

    // Step 4: Fill Year field
    // await page.fill('input[placeholder="yyyy"]:first', honor.year);

    // Step 5: Save
    // if (isLast) {
    //   await page.click('button:has-text("SAVE")');
    // } else {
    //   await page.click('button:has-text("SAVE & ADD ANOTHER")');
    // }
  }
}
