// ============================================
// SciENcv Biosketch - NIH Biographical Sketch Supplement
// Section A: Personal Statement
// Generated by Claude in Chrome browser extension
// ============================================

// SELECTORS
const PERSONAL_STATEMENT_SELECTORS = {
  addButton: 'button:contains("ADD PERSONAL STATEMENT")',
  textArea: 'textarea[aria-label*="Personal Statement"]', // or 'textbox' with label "Personal Statement *"
  saveButton: 'button:contains("SAVE")',
  cancelButton: 'button:contains("CANCEL")'
};

// DATA EXAMPLE
const personalStatement = {
  text: `I am a pulmonary and critical care physician, medical ethicist, and health services researcher who studies the allocation of scarce medical resources. My focus is absolute scarcity problems, where demand greatly exceeds supply, forcing healthcare systems to triage life-saving treatments using algorithmic policies. I use my comprehensive empirical and ethical training to evaluate allocation systems for a variety of these problems. My HealthCare Allocation lab's (HCA Lab) work on heart, kidney, life support, and vaccine allocation has led to high-impact publications in JAMA, JACC, AJRCCM, and the American Journal of Transplantation. I have received national recognition through young investigator awards from the American Society for Clinical Investigation and the American Thoracic Society. My original science and normative writing have been featured in USA Today, The Washington Post, and The New York Times. My work has been repeatedly cited by national and state policymakers tasked with creating systems for allocating scarce medical resources, and I am currently co-chair of the Scientific Registry of Transplant Recipients Analytic Methods Subcommittee. I am the founding executive director of the Common Longitudinal ICU data Format (CLIF) consortium, a growing network of ICU data science labs that develop and utilize the open-source CLIF data standard to perform privacy-preserving federated ICU data science.`
};

// AUTOMATION STEPS
async function addPersonalStatement(page) {
  // Step 1: Scroll to Personal Statement section
  // await page.scrollTo('text=A. Personal Statement');

  // Step 2: Click "ADD PERSONAL STATEMENT" button
  // await page.click('button:has-text("ADD PERSONAL STATEMENT")');

  // Step 3: Enter personal statement text
  // await page.fill('textarea', personalStatement.text);
  // Note: Character limit is 3,500

  // Step 4: Click "SAVE"
  // await page.click('button:has-text("SAVE")');
}
